### ISSUE TITLE
Profiler start but SSID isnt stable with TP-LINK archer T9UH v2 [RTK8814AU]

### ISSUE THREAD

**Issue by marcelkoedijk** [WLAN-Pi/profiler-legacy#3]
Dongle: TP-Link archer T9UH v2
Chipset: RTK8814AU
Driver: 88XXau v5.2.20.2_28373.20180619
Profiler: 1.3.0 - 1.5.0
WLAN-Pi: 1.7.1 beta && 1.6.1

When start profiler "sudo ./profiler.py -c 36 -s TEST" the script start as supposed and waiting for associations (will never happend). In Ekahau i see the SSID is unstable, transmitting for 5 seconds and then its gone again for say 30-60 seconds.

Could also be a chipset/driver issue, but monitor mode works fine in kismet and wlanpishark.

dmesg:
[ 3796.294408] usbcore: registered new interface driver rtl88xxau
[ 3838.755148] device wlan0 entered promiscuous mode
[ 3838.875926] tun: Universal TUN/TAP device driver, 1.6
[ 4156.470709] device wlan0 left promiscuous mode

**Comment by wifinigel** [comment]
We are currently only providing support for the CF-912. I don't think we can do much with this - sorry!
